SELECT DISTINCT T.*
FROM (
    SELECT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR(CAR.DAILY_FEE * 30 * (1-PLAN.DISCOUNT_RATE/100)) FEE
    FROM CAR_RENTAL_COMPANY_CAR AS CAR 
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON CAR.CAR_TYPE = PLAN.CAR_TYPE
    WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
    AND PLAN.DURATION_TYPE = '30일 이상'
    AND CAR.CAR_ID NOT IN (SELECT CAR_ID
                           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                           WHERE START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
                           OR END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
                            OR (START_DATE <= '2022-11-01' AND END_DATE >='2022-11-30'))
    )AS T
WHERE T.FEE BETWEEN 500000 AND 1999999
ORDER BY T.FEE DESC, T.CAR_TYPE ASC, T.CAR_ID DESC

# AND HISTORY.START_DATE > '2022-11-30' OR HISTORY.END_DATE < '2022-11-01'
# AND PLAN.DURATION_TYPE = '30일 이상' ) T
# WHERE T.FEE BETWEEN 500000 AND 1999999