# -- 코드를 입력하세요
WITH TEMP AS (SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE MONTH(START_DATE) BETWEEN '08' AND '10'
              GROUP BY CAR_ID
              HAVING COUNT(*) >= 5 )

SELECT DISTINCT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) OVER(PARTITION BY MONTH(START_DATE), CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM TEMP) 
    AND MONTH(START_DATE) BETWEEN '08' AND '10'
ORDER BY 1, 2 DESC;