-- 코드를 입력하세요
SELECT SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM 
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, COALESCE(NULL, NULL) AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
UNION ALL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE) T
WHERE SALES_DATE LIKE '2022-03-%%'
GROUP BY SALES_DATE, PRODUCT_ID, USER_ID
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID ASC