-- 코드를 입력하세요
WITH MXV AS(
   SELECT BOARD_ID FROM USED_GOODS_BOARD WHERE VIEWS = (SELECT MAX(VIEWS)
                                                        FROM USED_GOODS_BOARD)
)
SELECT CONCAT('/home/grep/src/',BOARD_ID, '/',FILE_ID,FILE_NAME,FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (SELECT * FROM MXV)
ORDER BY FILE_ID DESC;