-- 코드를 입력하세요
WITH FH AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL1
    FROM FIRST_HALF 
    GROUP BY FLAVOR
),
J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL2
    FROM JULY 
    GROUP BY FLAVOR
)
SELECT FLAVOR
FROM  FH LEFT JOIN J USING(FLAVOR)
ORDER BY TOTAL1+TOTAL2 DESC
LIMIT 3;