-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, T.CATEGORY, SUM(T.PRICE * T.SALES)
FROM AUTHOR INNER JOIN (
SELECT BOOK_SALES.BOOK_ID, BOOK_SALES.SALES, BOOK.AUTHOR_ID, BOOK.CATEGORY, BOOK.PRICE
FROM BOOK
INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01-%%'
) T ON AUTHOR.AUTHOR_ID = T.AUTHOR_ID
GROUP BY AUTHOR.AUTHOR_ID, T.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, T.CATEGORY DESC