-- 코드를 입력하세요
SELECT USED_GOODS_BOARD.TITLE, USED_GOODS_BOARD.BOARD_ID, USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, TO_CHAR(USED_GOODS_REPLY.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_REPLY LEFT OUTER JOIN USED_GOODS_BOARD ON USED_GOODS_REPLY.BOARD_ID = USED_GOODS_BOARD.BOARD_ID
WHERE TO_CHAR(USED_GOODS_BOARD.CREATED_DATE,'YYYYMMDD') >= '20221001' AND TO_CHAR(USED_GOODS_BOARD.CREATED_DATE,'YYYYMMDD') <= '20221031'
ORDER BY USED_GOODS_REPLY.CREATED_DATE, TITLE